spring.application.name=redis

spring.cache.type=redis

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sunjajp1472@gmail.com
spring.mail.password=qmby orei ftjy noll
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

mail-random-value=basiliumShoppingMall