#--------------------------------------------------------------------------------#
# StaticBlockConfig ???? DEBUG ??
logging.level.basilium.basiliumserver.global.configuration.StaticBlockConfig=DEBUG
# logging.level.basilium.basiliumserver.global.configuration=DEBUG

#--------------------------------------------------------------------------------#
### Hibernate JDBC
# Writing(batch insert/update)
spring.jpa.properties.hibernate.jdbc.batch_size=50
# Reading(Lazy loading collection batch) @BatchSize
spring.jpa.properties.hibernate.default_batch_fetch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# MYSQL DB
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# time: utc ->
# spring.datasource.url=jdbc:mysql://localhost:3306/basilium?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.url=jdbc:mysql://localhost:3306/basilium?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=basilium
spring.datasource.password=pjhcsol
# p6 spy DB LOG driver
#spring.datasource.driver-class-name=com.p6spy.engine.spy.P6SpyDriver
#spring.datasource.url=jdbc:p6spy:mysql://localhost:3306/basilium?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8

#LOG
# ?? ?? -> info? debug? ???? url ?? x
logging.level.org.apache.coyote.http11=trace
server.tomcat.reject-illegal-header=true
# 1) ?? ?? ?? (root) ? INFO
logging.level.root=INFO
# 2) Hibernate? ???? SQL ??? DEBUG == #JPA spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
# ???? ???
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# (??) ?? ?? ??? ??
logging.level.org.hibernate.type=TRACE

# Spring Data JPA ?? ?? ??
logging.level.org.springframework.data.jpa.repository.query=DEBUG
# (??) ?? ?? ????? ??
logging.level.org.springframework.data.jpa.repository.support=TRACE

# JPA
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#Hibernate: DB LOG
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.defer-datasource-initialization=true

# ddl-auto (create,update)
#spring.jpa.hibernate.ddl-auto=create-drop

# schema.sql and data.sql into dataSource
#spring.sql.init.schema-locations=classpath:schema.sql
#spring.sql.init.data-locations=classpath:data.sql
#spring.sql.init.mode=always
#--------------------------------------------------------------------------------#

# HTTPS ??
#server.port=8443

# keystore.p12 ?? ? ????
#server.ssl.key-store=
#server.ssl.key-store-password=
#server.ssl.key-store-type=
#server.ssl.key-alias=

# ??? ?? ?? (???? ???? ??)
#server.forward-headers-strategy=framework
#--------------------------------------------------------------------------------#

server.port = 8080
spring.devtools.restart.enabled=false
#spring.devtools.livereload.enabled=false
#spring.mvc.async.request-timeout=60000
server.tomcat.connection-timeout=60000
spring.mvc.async.request-timeout=60000

#--------------------------------------------------------------------------------#
#JVM properties or VM option edit
#prd
#JAVA_OPTS="-Xms512m -Xmx16384m"
#stg
JAVA_OPTS="-Xms512m -Xmx8192m"

# -Java RMI(Remote Method Invocation) ? ??? ?? ??
# -RMI? ?? ??? ??? ? ??? ???(? ?? RMI ??·UID·ObjID ?)? ???????? ?? ??????
# -???(name), codebase, defaultLoader? ?? ?????? ?? ?? ?? ??
#logging.level.sun.rmi=INFO
#logging.level.remote.rmi=INFO
# -javax.management.remote.rmi ???? DEBUG ?? ??
#logging.level.javax.management.remote.rmi=INFO

#--------------------------------------------------------------------------------#
# DB connection
spring.jpa.open-in-view=false
# pool size = Tn x (Cm - 1) + 1 #warn: Thread starvation or clock leap detected
spring.datasource.hikari.maximum-pool-size=24

# HikariPool ?? ? stats, fill-pool ??? DEBUG ? ??
# logging.level.com.zaxxer.hikari.pool.HikariPool=DEBUG
# -(??) Hikari ??? ?? ? ???? ?? ???
# logging.level.com.zaxxer.hikari=DEBUG

#--------------------------------------------------------------------------------#
#thymeleaf
spring.thymeleaf.check-template-location=false

#--------------------------------------------------------------------------------#
# userImage upload dir
# uploadDir = /Users/gimseungjun/Desktop/BE/VirtualFitting_System/basilium-server/src/main/java/basilium/basiliumserver/userImageStorage/
#uploadDir = /Users/hansol/Desktop/VirtualFitting_System/basilium-server/src/main/java/basilium/basiliumserver/userImageStorage/
#profileDir = /Users/hansol/Desktop/VirtualFitting_System/basilium-server/src/main/java/basilium/basiliumserver/userProfileImageStorage/

# 1) ?? ??? ?? ??
image.upload-dir=basilium-server/src/main/resources/userImageStorage/
image.profile-dir=basilium-server/src/main/resources/userProfileImageStorage/
image.review-dir=basilium-server/src/main/resources/userReviewImageStorage/
image.brand-dir=basilium-server/src/main/resources/businessCertificateImageStorage/

# 2) image ??? or ip -> db insert ??? ?? ? db ?? ??
image.domain-url=basilium.co.kr/

# 2-1) DB? ??? ??? URL prefix? -> db ?? url -> UserImageResourceConfig
image.domain-upload-dir=b1/images/userImageStorage/
image.domain-profile-dir=b1/images/userProfileImageStorage/
image.domain-review-dir=b1/images/userReviewImageStorage/
image.domain-brand-dir=b1/images/businessCertificateImageStorage/

#image.domain-upload-dir=basilium.co.kr/b1/images/userImageStorage/
#image.domain-profile-dir=basilium.co.kr/b1/images/userProfileImageStorage/
#image.domain-review-dir=basilium.co.kr/b1/images/userReviewImageStorage/

#/Users/hansol/Desktop/VirtualFitting_System/basilium-server/src/main/resources/userImageStorage
#/Users/hansol/Desktop/VirtualFitting_System/basilium-server/src/main/resources/userProfileImageStorage

#--------------------------------------------------------------------------------#
jwt.secret=VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
jwt.access-token-validity=3600000
jwt.refresh-token-validity=86400000

#--------------------------------------------------------------------------------#
# Multipart ??
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=2GB

#--------------------------------------------------------------------------------#
#s3 git
cloud.aws.credentials.accessKey=bean
cloud.aws.credentials.secretKey=bean
cloud.aws.stack.auto=false

# AWS S3 Service bucket
cloud.aws.s3.bucket=
cloud.aws.region.static=ap-northeast-2

# AWS S3 Bucket URL
cloud.aws.s3.bucket.url=

#--------------------------------------------------------------------------------#
#import git
imp.code=
imp.api.key=
imp.api.secretkey=

#--------------------------------------------------------------------------------#
# Oauth-google
social.client.google.rest-api-key=temp
social.client.google.secret-key=temp
social.client.google.redirect-uri=temp
social.client.google.grant_type=authorization_code
# Oauth-kakao
social.client.kakao.rest-api-key=temp
social.client.kakao.redirect-uri=temp
social.client.kakao.grant_type=authorization_code
# Oauth-naver
social.client.naver.rest-api-key=temp
social.client.naver.secret-key=temp
social.client.naver.redirect-uri=temp
social.client.naver.grant_type=authorization_code

#--------------------------------------------------------------------------------#
#MYSQL, kafkaMQ ??
# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Broker
spring.kafka.admin.fail-fast=false

# AdminClient
spring.kafka.admin.properties.request.timeout.ms=60000
spring.kafka.admin.properties.retry.backoff.ms=1000
spring.kafka.admin.properties.metadata.max.age.ms=30000

# -Spring-Kafka ListenerContainer DEBUG ??? INFO? ??
#logging.level.org.springframework.kafka.listener.KafkaMessageListenerContainer=INFO
#logging.level.org.springframework.kafka.listener=INFO

# -Kafka client DEBUG ??? INFO? ??
#logging.level.org.apache.kafka.clients.consumer=INFO
#logging.level.org.apache.kafka.clients.FetchSessionHandler=INFO
#logging.level.org.apache.kafka.clients.NetworkClient=INFO

#kafkaMQ
#kafka.bootstrapAddress=localhost:9092
#message.topic.name=mytopic
#greeting.topic.name=greeting
#filtered.topic.name=filtered
#partitioned.topic.name=partitioned

#RabbitMQ
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest

#--------------------------------------------------------------------------------#