export const products = [
    {
      id: 1,
      name: "Crown Silver Hoodie",
      price: '72,000',
      discountRate: 20,
      discountedPrice: '57,600',
      brand : "바실리움",
      image: "/img/product/product_sample_1.png",
      availableSizes: ["XS", "S", "M", "L", "XL",],
      colors: ["#000000", "#FFFFFF", "#FF0000", "#00FF00", "#0000FF"],
      materials: ["COTTON", "POLYESTER"],
    },
    {
      id: 2,
      name: "Crown Silver Hoodie",
      price: '72,000',
      discountRate: 0,
      brand : "BASILIUM",
      image: "/img/product/product_sample_2.png",
      availableSizes: ["M", "L"],
      colors: ["#000000", "#FFFFFF", "#FF0000", "#00FF00", "#0000FF"],
      materials: ["COTTON", "POLYESTER"],
    },
    {
      id: 3,
      name: "Crown Silver Hoodie",
      price: '72,000',
      discountRate: 0,
      brand : "BASILIUM",
      image: "/img/product/product_sample_3.png",
      availableSizes: ["M", "L"],
      colors: ["#000000", "#FFFFFF", "#FF0000", "#00FF00", "#0000FF"],
      materials: ["COTTON", "POLYESTER"],
    },
    {
    id: 4,
    name: "Crown Silver Hoodie",
    price: '72,000',
    discountRate: 50,
    discountedPrice: '36,000',
    brand : "BASILIUM",
    image: "/img/product/product_sample_1.png",
    availableSizes: ["M", "L"],
    colors: ["#000000", "#FFFFFF", "#FF0000", "#00FF00", "#0000FF"],
    materials: ["COTTON", "POLYESTER"],
    },
    {
    id: 5,
    name: "Crown Silver Hoodie",
    price: '72,000',
    discountRate: 10,
    discountedPrice: '64,800',
    brand : "BASILIUM",
    image: "/img/product/product_sample_2.png",
    availableSizes: ["M", "L"],
    colors: ["#000000", "#FFFFFF", "#FF0000", "#00FF00", "#0000FF"],
    materials: ["COTTON", "POLYESTER"],
    },
  ];
  
